### ISSUE TITLE
typescript example blog rendering of text, images and youtube videos

### ISSUE THREAD

**Issue by humberni** [portabletext/react-portabletext#31]
A real example from a blog with next js, typescript and sanity of how to render text, images and youtube videos would be very helpful. If anyone has an example, it would be greatly appreciated, since I find the @portabletext/react guides a bit confusing and they generate errors. Thank you very much.

**Comment by humberni** [comment]
Please share your example I managed to render videos but with the obsolete package

@sanity/block-content-to-react

**Comment by keplux** [comment]
I just threw something together. There may or may not be a better way to do this, but this is super simple. The article is a perfectly fine starting point. I'm using Studio v3, but I don't recall any major differences in this process if you're on v2.

# Sanity
## First, create your schema.
```ts
export default defineType({
  name: 'video',
  title: 'Video',
  type: 'object',
  fields: [
    {
      name: 'videoId',
      title: 'Video ID',
      type: 'string',
    },
    // ...other information you want to collect (title, video options, etc.)
  ],
});
```

### Then add it to your main schema export like you would for any others.
No example, this is standard Sanity use.

### Now add the video type to the array for your block content.
```ts
{
  name: 'description',
  title: 'Description',
  type: 'array',
  of: [{ type: 'block' }, { type: 'video' }],
},
```

### Your video object will appear in the block content pane.
![Screenshot 2022-12-01 at 3 06 29 PM](https://user-images.githubusercontent.com/100491330/205149607-b2caf9c6-4cf5-4e99-8a99-6cc9097ac39d.png)

## Get the ID from your YouTube video and add it to a new video block.
![Screenshot 2022-12-01 at 3 09 25 PM](https://user-images.githubusercontent.com/100491330/205149872-cea6595d-05b7-45f1-ac69-6c4ddc66fbdc.png)
![Screenshot 2022-12-01 at 3 09 51 PM](https://user-images.githubusercontent.com/100491330/205149886-5d514546-a2e3-4ae2-8165-a0026f96d297.png)

And that's all you need to do from a Sanity standpoint. If that's confusing, you should go back through their docs since that's the very basics.

# Next.js and @portabletext/react
I haven't experimented with custom component keys until now--so if I can do it, so can you! :)

## Update the PortableText components object to show a custom YouTube embed component
I just installed [`react-youtube`](https://www.npmjs.com/package/react-youtube) for this:

1.  `npm i react-youtube`

2.  Fetch your block content resource from Sanity using whichever method you choose, and pass it to `PortableText`.

3.  Add YouTube component to types object. The key should match the name of the object type we previously created--in this case `video`. The `{value}` parameter is the data from that object, so we can easily access the video ID we stored in the `videoId` field.

```ts
import YouTube from 'react-youtube';

// ...
  <PortableText
    value={blockContentFetchedFromSanity}
    components={{
      marks: { ... },
      blocks: { ... },
      // What we're interested in
      types: {
        video: ({value}) => <YouTube videoId={value.videoId} />
      }
    }}
  />
// ...
```

## Celebrate
You should now see the video on your front end!
![Screenshot 2022-12-01 at 3 30 50 PM](https://user-images.githubusercontent.com/100491330/205153439-c74d45e7-1400-473f-9f58-3fcd93cf8141.png)

Let me know if you're confused about any of this, and I'll be happy to point you in the direction of resources.

**Comment by humberni** [comment]
Thank you very much for the contribution.
